### ISSUE TITLE
Issues with the floodcase_202107

### ISSUE THREAD

**Issue by ssomani10** [WAM2layers/WAM2layers#193]
I installed the WAM2Layers, and tried to run  floodcase_202107.yaml by keeping everything the same on my Mac computer.  I obtain the following error shown below:

(wamenv) shaffiqsomani@MacBook-Pro ~ % wam2layers backtrack floodcase_202107.yaml
Welcome to WAM2layers.
Starting backtrack experiment.
Initializing experiment with config file floodcase_202107.yaml
Traceback (most recent call last):
  File "/Users/shaffiqsomani/anaconda3/envs/wamenv/bin/wam2layers", line 8, in <module>
    sys.exit(cli())
  File "/Users/shaffiqsomani/anaconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shaffiqsomani/anaconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/shaffiqsomani/anaconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shaffiqsomani/anaconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shaffiqsomani/anaconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shaffiqsomani/WAM2layers/src/wam2layers/tracking/backtrack.py", line 537, in cli
    run_experiment(config_file)
  File "/Users/shaffiqsomani/WAM2layers/src/wam2layers/tracking/backtrack.py", line 467, in run_experiment
    config, region, output = initialize(config_file)
  File "/Users/shaffiqsomani/WAM2layers/src/wam2layers/tracking/backtrack.py", line 400, in initialize
    config = Config.from_yaml(config_file)
  File "/Users/shaffiqsomani/WAM2layers/src/wam2layers/config.py", line 318, in from_yaml
    return cls(**settings)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for Config
filename_template
  field required (type=value_error.missing)
input_frequency
  field required (type=value_error.missing)
output_frequency
  field required (type=value_error.missing)
level_type
  field required (type=value_error.missing)
levels
  field required (type=value_error.missing)
log_level
  field required (type=value_error.missing)

**Comment by ssomani10** [comment]
I tried using the miniconda and installed the software.  Had no issues when I used the which wam2layers and wam2layers --help.  When I tried to run the software, I obtained the following errors:

(base) shaffiqsomani@MacBook-Pro Documents % conda activate wamenv
(wamenv) shaffiqsomani@MacBook-Pro Documents % wam2layers backtrack floodcase_202107.yaml
Welcome to WAM2layers.
Starting backtrack experiment.
Initializing experiment with config file floodcase_202107.yaml
Traceback (most recent call last):
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/bin/wam2layers", line 8, in <module>
    sys.exit(cli())
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/wam2layers/tracking/backtrack.py", line 553, in cli
    run_experiment(config_file)
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/wam2layers/tracking/backtrack.py", line 485, in run_experiment
    config, region, output = initialize(config_file)
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/wam2layers/tracking/backtrack.py", line 419, in initialize
    config = parse_config(config_file)
  File "/Users/shaffiqsomani/miniconda3/envs/wamenv/lib/python3.9/site-packages/wam2layers/tracking/backtrack.py", line 23, in parse_config
    freq=config["input_frequency"],
KeyError: 'input_frequency'


Do. you have any suggestion, or does this need to be run in Linux.  Thanks.

**Comment by Peter9192** [comment]
Hi @ssomani10, welcome and thanks for reaching out! I think the example case is a bit outdated. There were some recent changes in the configuration setup, also see https://github.com/WAM2layers/WAM2layers/issues/181. 

We should arrive at a more stable configuration for the final V3 release. For now, I recommend you carefully monitor the issue tracker and the corresponding documentation: https://wam2layers.readthedocs.io/en/latest/config.html 

PS: There's a related discussion here (which might not be the best place): https://github.com/WAM2layers/WAM2layers/discussions/186#discussioncomment-5310892

**Comment by Peter9192** [comment]
The last issue you reported seems to be related to the fact that the example data you used is also outdated. I'll see if I can update that soon.

**Comment by ssomani10** [comment]
Thanks so much.
