### ISSUE TITLE
Monthly data preprocessing

### ISSUE THREAD

**Issue by cowboy123321** [WAM2layers/WAM2layers#199]
I downloaded the monthly average reanalysis data by modifying the era5 data download code, and wanted to do an annual water vapor trace, but an error occurred when running the preprocessing code:
Traceback (most recent call last):
  File "D:\miniconda3\envs\wamenv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda3\envs\wamenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\miniconda3\envs\wamenv\Scripts\wam2layers.exe\__main__.py", line 7, in <module>
  File "D:\miniconda3\envs\wamenv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\miniconda3\envs\wamenv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\miniconda3\envs\wamenv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\miniconda3\envs\wamenv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\miniconda3\envs\wamenv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\miniconda3\envs\wamenv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\miniconda3\envs\wamenv\lib\site-packages\wam2layers\preprocessing\era5.py", line 348, in cli
    prep_experiment(config_file)
  File "D:\miniconda3\envs\wamenv\lib\site-packages\wam2layers\preprocessing\era5.py", line 249, in prep_experiment
    dp, p, q, u, v, pb = get_dp_pressurelevels(q, u, v, sp, q2m, u10, v10)
  File "D:\miniconda3\envs\wamenv\lib\site-packages\wam2layers\preprocessing\era5.py", line 152, in get_dp_pressurelevels
    u = insert_level(u, interpolate(p_boundary, p, u), 150000)
  File "D:\miniconda3\envs\wamenv\lib\site-packages\wam2layers\preprocessing\shared.py", line 185, in interpolate
    if np.any(x[None, ...] < xp[0, ...]):
ValueError: operands could not be broadcast together with shapes (1,421,901) (22,901)

How should this be resolved? I look forward to your reply.

**Comment by Peter9192** [comment]
Hi @cowboy123321, welcome to WAM2layers! 

It looks like a shape mismatch, so somehow the data that's read in the pre-processing script is not the same shape as was expected. What did you change in the download script? Have you checked the downloaded data? What are the dimensions? Can you load one of the era5 files, e.g. with xarray, print it, and copy the output here? Also, monthly data may be far too coarse for doing a tracking experiment with WAM2layers, not only because it is too much smoothed, but also because the model needs to run at a short timestep for numerical stability.

**Comment by cowboy123321** [comment]
I see. Thank you.
