### ISSUE TITLE
Error calling visualization function

### ISSUE THREAD

**Issue by geek-yang** [WAM2layers/WAM2layers#245]
There is an error when calling `wam2layers visualize input floodcase_202107.yaml` after running the example case from tutorial (https://wam2layers.readthedocs.io/en/latest/userguide.html#analysis-and-visualization):

```py
❯ wam2layers visualize input floodcase_202107.yaml
Traceback (most recent call last):
  File "/home/yangliu/mambaforge/envs/wamenv/bin/wam2layers", line 8, in <module>
    sys.exit(cli())
  File "/home/yangliu/mambaforge/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/yangliu/mambaforge/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/yangliu/mambaforge/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yangliu/mambaforge/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yangliu/mambaforge/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yangliu/mambaforge/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/yangliu/WAM2layers/WAM2layers/src/wam2layers/analysis/visualization.py", line 244, in input
    visualize_input_data(config_file)
  File "/home/yangliu/WAM2layers/WAM2layers/src/wam2layers/analysis/visualization.py", line 111, in visualize_input_data
    _plot_precip(config, ax)
  File "/home/yangliu/WAM2layers/WAM2layers/src/wam2layers/analysis/visualization.py", line 45, in _plot_precip
    freq=config[
TypeError: 'Config' object is not subscriptable
```

**Comment by geek-yang** [comment]
Also, it seems that the CD/CI only covers the process upto the `backtrack`. Maybe better to add visualization module to the pipeline as well.
https://github.com/WAM2layers/WAM2layers/blob/f69936f354145d3bd58b67ec74c9d2ba42ef6bb3/.github/workflows/ci.yaml#L34-L39
