### ISSUE TITLE
PRESSURE_LEVEL ERA5 DATA 

### ISSUE THREAD

**Issue by 1277820238** [WAM2layers/WAM2layers#314]
We downloaded the global data based on the code you provided for downloading pressure_level data, but we are having this issue when we are doing the preprocessing:

```
Traceback (most recent call last):
  File "/public/home/ganjunwei/.conda/envs/wamenv/bin/wam2layers", line 8, in <module>
    sys.exit(cli())
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/wam2layers/cli.py", line 130, in era5
    prep_experiment(config_file)
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/wam2layers/preprocessing/era5.py", line 258, in prep_experiment
    dp, p, q, u, v, pb = get_dp_pressurelevels(q, u, v, sp, q2m, u10, v10)
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/wam2layers/preprocessing/era5.py", line 167, in get_dp_pressurelevels
    u = insert_level(u, interpolate(p_boundary, p, u), 150000)
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/wam2layers/preprocessing/shared.py", line 189, in interpolate
    if np.any(x[None, ...] < xp[0, ...]):
ValueError: operands could not be broadcast together with shapes (1,721,1440) (22,1440) 
```

We found that the problem looks like it might be happening inside **wam2layers/preprocessing/shared.py**， but we don't know how to make the right changes:
```
def interpolate(x, xp, fp, axis=1, descending=False):
    """Linearly interpolate along an axis of an N-dimensional array.

    This function interpolates one slice at a time, i.e. if xp and fp are 4d
    arrays, x should be a 3d array and the function will return a 3d array.

    It is assumed that the input array is monotonic along the axis.
    """
    # Cast input to numpy arrays
    x = np.asarray(x)
    xp = np.asarray(xp)
    fp = np.asarray(fp)

    # Move interpolation axis to first position for easier indexing
    xp = np.moveaxis(xp, axis, 0)
    fp = np.moveaxis(fp, axis, 0)

    # Handle descending axis
    if descending:
        xp = np.flip(xp, axis=0)
        fp = np.flip(fp, axis=0)
        assert (
            np.diff(xp, axis=0).min() >= 0
        ), "with descending=False, xp must be monotonically decreasing"
    else:
        assert (
            np.diff(xp, axis=0).min() >= 0
        ), "with desciending=True, xp must be monotonically increasing"

    # Check for out of bounds values
    if np.any(x[None, ...] < xp[0, ...]):
        raise ValueError("one or more x are below the lowest value of xp")
    if np.any(x[None, ...] > xp[-1, ...]):
        raise ValueError("one or more x are above the highest value of xp")
    # print("complete")
    # Find indices such that xp[lower] < x < xp[upper]  
    upper = np.sum(x > xp, axis=0)
    lower = upper - 1

    # This will allow numpy advanced indexing to take an (N-1)D slice of an ND array
    upper = (upper, *np.meshgrid(*[range(l) for l in x.shape], indexing="ij"))
    lower = (lower, *np.meshgrid(*[range(l) for l in x.shape], indexing="ij"))

    fy = fp[lower] + (fp[upper] - fp[lower]) * (x - xp[lower]) / (xp[upper] - xp[lower])
    return fy
```

We especially want to ask you for help!

**Comment by Peter9192** [comment]
Thanks for reaching out and sharing your experience. I can try to guide you through the debugging process. 

Let's focus on the last few lines of the stack trace.

```
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/wam2layers/preprocessing/era5.py", line 167, in get_dp_pressurelevels
    u = insert_level(u, interpolate(p_boundary, p, u), 150000)
  File "/public/home/ganjunwei/.conda/envs/wamenv/lib/python3.9/site-packages/wam2layers/preprocessing/shared.py", line 189, in interpolate
    if np.any(x[None, ...] < xp[0, ...]):
ValueError: operands could not be broadcast together with shapes (1,721,1440) (22,1440) 
```

We can conclude that there is a shape mismatch, triggered on line 189 in shared.py, where the input `x[None, ....]` is compared to the variable `xp[0, ...]`. Inside this funcion `interpolate`, `x` and `xp` refer to `p_boundary` and `p`, as you can see from this line in the stack trace, where `interpolate` is called: `u = insert_level(u, interpolate(p_boundary, p, u), 150000)`

Now, `p` is expected to be three-dimensional here (level/lat/lon), whereas `p_boundary` is expected to be two-dimensional (lat/lon). The goal of this check is to guarantee that ll values of `p_boundary` are within the values of `p`, i.e. we don't have to extrapolate. The code wants to compare it to the first level.

Judging from the printed shape, I guess the order of your coordinates is different from what is assumed in the code. Could it be that it is lat/level/lon instead of level/lat/lon? You can confirm this by adding debug statements in your code. The easiest is this:

Inside the `interpolate` function, before the line that triggers the error, insert the following line of code: `import IPython; IPython.embed(); quit()` Then run your code. As soon as it encounters this line, it will start an interactive IPython session, so you can look around, print the values of `x` and `xp`, et cetera. Alternatively, you could insert print statements or log messages.

Let me know if you get any new info from this.

PS do you have a name? It's nicer to engage with people than numbers :-)

**Comment by ruudvdent** [comment]
I am transfering this to the discussion pages.
